### ISSUE TITLE
How can I enroll to the course?

### ISSUE THREAD

**Issue by RiccardoAgabiti** [erodola/DLAI-s2-2022#2]

**Comment by RiccardoAgabiti** [comment]
I'm a Data Science student at Sapienza

**Comment by erodola** [comment]
There is no need to enroll. Just show up at the lectures and register on Infostud for the exam when the time comes.

**Comment by erodola** [comment]
To us teachers, it doesn't matter: lessons are public, anyone can attend, and as long as you can register on Infostud, you can take the exam. However, I don't know what kind of administrative obligations you have as an Erasmus student, or whether you have to register somehow formally that you are going to take this exam; please check with the administration office!
